version: "3"

services:
  mssql-server:
    container_name: mssql-server
    image: "mcr.microsoft.com/mssql/server"
    restart: "always"
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "yourStrong("
      # userid = 'sa'
